on: push

jobs:
   job1:
     runs-on: ubuntu-latest
     steps:
       - run: pwd
       - run: ls
   job2:
     runs-on: ubuntu-latest
     steps:
       - run: cat /etc/os-release
       - run:    
		wget https://dl.google.com/android/repository/android-ndk-r21e-linux-x86_64.zip
		sudo unzip -q android-ndk-r21e-linux-x86_64.zip -d /usr/local
		echo "ANDROID_NDK_HOME=/usr/local/android-ndk-r21e" >> $GITHUB_ENV
		echo "$ANDROID_NDK_HOME" >> $GITHUB_PATH
		echo "LD_LIBRARY_PATH=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/lib64:$LD_LIBRARY_PATH" >> $GITHUB_ENV
		ndk-build  -v
